server {
    listen 80;
    server_name secure-tasm.lozdo.com;
    server_tokens off;

    # Frontend (static vue)
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Proxy to backend
    location ~ ^/(api|auth)/ {
        resolver 127.0.0.11 valid=30s;
        set $upstream_backend http://app:3000;
        proxy_pass $upstream_backend;

        proxy_hide_header Server;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
        proxy_set_header Cookie $http_cookie;
        proxy_pass_header Set-Cookie;

        proxy_connect_timeout 90s;
        proxy_read_timeout    90s;
        proxy_send_timeout    90s;
    }
}